CREATE TABLE tb_url (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    url_code VARCHAR(7) NOT NULL,
    access_count BIGINT DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_tb_url PRIMARY KEY (id),
    CONSTRAINT uc_tb_url_url_code UNIQUE (url_code)
);